config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "follows" => "relationships#follows", as: "follows"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "search" => "searches#search", as: "search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :shop_name, presence: true
  validates :image, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def self.search_for(content, method)
    if method == "perfect"
      PostImage.where(shop_name: content)
    elsif method == "forword"
      PostImage.where("shop_name LIKE ?", content + "%")
    elsif method == "backword"
      PostImage.where("shop_name LIKE ?", "%" + content)
    elsif method == "partial"
      PostImage.where("shop_name LIKE ?", "%" + content + "%")
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search_for(content, method)
    if method == "perfect"
      User.where(name: content)
    elsif method == "forword"
      User.where("name LIKE ?", content + "%")
    elsif method == "backword"
      User.where("name LIKE ?", "%" + content)
    elsif method == "partial"
      User.where("name LIKE ?", "%" + content + "%")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = Favorite.new(post_image_id: @post_image.id)
    favorite.user_id = current_user.id
    favorite.save
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: @post_image.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @post_image = PostImage.find(params[:post_image_id])
    post_comment = PostComment.new(post_comment_params)
    post_comment.user_id = current_user.id
    post_comment.post_image_id = @post_image.id
    post_comment.save
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    post_comment = PostComment.find(params[:id])
    post_comment.destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.all
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:image, :shop_name, :caption)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.new(follower_id: params[:user_id])
    follow.save
    redirect_to request.referer
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to request.referer
  end

  def follows
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @content = params[:content]
    @model = params[:model]
    @method = params[:method]
    if @model == "user"
      @records = User.search_for(@content, @method)
    elsif @model == "post_image"
      @records = PostImage.search_for(@content, @method)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if post_image.favorited_by?(current_user) %>
  <%= link_to post_image_favorites_path(post_image.id), method: :delete, remote: true do %>
    💖 <%= post_image.favorites.count %>
  <% end %>
<% else %>
  <%= link_to post_image_favorites_path(post_image.id), method: :post, remote: true do %>
    💙 <%= post_image.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn").html("<%= j(render "favorites/favorite", post_image: @post_image) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn").html("<%= j(render "favorites/favorite", post_image: @post_image) %>");

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/post_comments/_post_comment.html.erb
<%= post_image.post_comments.count %>件コメント
<% post_image.post_comments.each do |post_comment| %>
  <%= image_tag post_comment.user.get_profile_image(40 ,40) %>
  <%= post_comment.created_at.strftime("%Y/%m/%d") %>
  <%= post_comment.comment %>
  <%= post_comment.comment %>
  <%= link_to "削除", post_image_post_comment_path(post_comment.post_image.id, post_comment.id), method: :delete, remote: true %>
<% end %>

app/views/post_comments/create.js.erb
$('textarea').val("");
$("#comment").html("<%= j(render 'post_comments/post_comment', post_image: @post_image) %>");

app/views/post_comments/destroy.js.erb
$("#comment").html("<%= j(render 'post_comments/post_comment', post_image: @post_image) %>");

app/views/post_images/_list.html.erb
<% post_images.each do |post_image| %>
  <%= link_to post_image_path(post_image.id) do %>
    <%= image_tag post_image.get_image %>
  <% end %>
  <%= image_tag post_image.user.get_profile_image(40, 40) %>
  <%= link_to post_image.shop_name, post_image_path(post_image.id) %>
  説明: <%= post_image.caption %>
  By <%= post_image.user.name %>
  フォロー数: <%= post_image.user.followings.count %>
  フォロワー数: <%= post_image.user.followers.count %>
  <% if current_user != post_image.user %>
    <% if post_image.user.followed_by?(current_user) %>
      <%= link_to "フォロー外す", user_relationships_path(post_image.user.id), method: :delete %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(post_image.user.id), method: :post %>
    <% end %>
  <% end %>
  <%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %>
<% end %>

app/views/post_images/index.html.erb
<%= render "list", post_images: @post_images %>

app/views/post_images/new.html.erb
<h2>画像投稿フォーム</h2>

<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <ul>
    <% @post_image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post_image do |f| %>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image, accept: "image/*" %>
  </div>

  <div class="field">
    <%= f.label :shop_name %><br />
    <%= f.text_field :shop_name %>
  </div>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_area :caption %>
  </div>
    <%= f.submit "投稿" %>
<% end %>

app/views/post_images/show.html.erb
<%= image_tag @post_image.get_image %>
<%= image_tag @post_image.user.get_profile_image(40, 40) %>
<%= link_to @post_image.shop_name, post_image_path(@post_image.id) %>
説明: <%= @post_image.caption %>
By <%= @post_image.user.name %>
<%= @post_image.created_at.strftime("%Y/%m/%d") %>
<%= link_to @post_image.post_comments.count, post_image_path(@post_image.id) %>
<div id="favorite-btn">
  <%= render "favorites/favorite", post_image: @post_image %>
</div>
<% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image.id), method: :delete %>
<% end %>
<dev id="comment">
  <%= render "post_comments/post_comment", post_image: @post_image %>
</dev>
<%= form_with model: [@post_image, @post_comment], local: false do |f| %>
  <%= f.text_area :comment %>
  <%= f.submit "送信する" %>
<% end %>

app/views/relationships/followers.html.erb
<% if @users.exists? %>
  <% @users.each do |user| %>
    <%= image_tag user.get_profile_image(40, 40) %>
    <%= user.name %>
    フォロー数: <%= user.followings.count %>
    フォロワー数: <%= user.followers.count %>
    <%= link_to "Show", user_path(user.id) %>
  <% end %>
<% else %>
  <p>フォロワーはいません</p>
<% end %>

app/views/relationships/follows.html.erb
<% if @users.exists? %>
  <% @users.each do |user| %>
    <%= image_tag user.get_profile_image(40, 40) %>
    <%= user.name %>
    フォロー数: <%= user.followings.count %>
    フォロワー数: <%= user.followers.count %>
    <%= link_to "Show", user_path(user.id) %>
  <% end %>
<% else %>
  <p>フォロー中のユーザーはいません</p>
<% end %>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({"User" => "user", "Post" => "post_image"}) %>
    <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forword", "後方一致" => "backword", "部分一致" => "partial"}) %>
    <%= f.submit "検索" %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == "user" %>
  <h2>Users search for "<%= @content %>"</h2>
  <% @records.each do |record| %>
    <%= link_to user_path(record.id) do %>
      <%= image_tag record.get_profile_image(40, 40) %>
      <%= record.name %>
    <% end %>
  <% end %>
<% elsif @model == "post_image" %>
  <h2>Post search for "<%= @content %>"</h2>
  <% @records.each do |record| %>
    <%= link_to post_image_path(record.id) do %>
      <%= image_tag record.get_image %>
      <%= record.shop_name %>
    <% end %>
    <%= record.caption %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h4>プロフィール編集</h4>

<%= form_with model: @user do |f| %>
  <%= f.text_field :name, autofocus: true %>
  <%= image_tag @user.get_profile_image(40, 40) %>
  <%= f.file_field :profile_image, accept: "image/*" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<%= image_tag @user.get_profile_image(70, 70) %>
<%= @user.name %>
<% if @user == current_user %>
  <%= link_to "プロフィール編集", edit_user_path(@user.id) %>
  follows <%= link_to @user.followings.count, user_follows_path(@user.id) %>
  followers <%= link_to @user.followers.count, user_followers_path(@user.id) %>
<% end %>

<%= render "post_images/list", post_images: @post_images %>